
server:
  port: 8092
  forward-headers-strategy: framework

jw:
  secret:
    key: 586E3272357538782F413F4428472B4B6250655368566B597033733676397924
  time:
    expiration: 3600000 #una hora

spring:
  application:
    name: micro-service-auth

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-d4ieee4hg0os739sbkf0-a.virginia-postgres.render.com:5432/proyecto_microservicesdb
    username: carta87
    password: QxSTq1RBRRCrRQmD7qFUmYM87ASwGlM0

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZooServer: http://localhost:8761/eureka

springdoc:
  version: '@springdoc.version@'
  api-docs:
    version: openapi_3_1
  cache:
    disabled: true