server:
  port: 8761

spring:
  application:
    name: micro-service-eureka

eureka:
  instance:
    hostname: ${RENDER_EXTERNAL_URL}   # Render pone la URL real en tiempo de ejecución

  client:
    register-with-eureka: false        # Eureka NO se registra a sí mismo
    fetch-registry: false
    service-url:
      defaultZone: ${RENDER_EXTERNAL_URL}/eureka/